version: '3'

services:
  db:
    image: mysql:5.7
    container_name: vzlove_db
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306

  vzlove:
    build: .
    container_name: vzlove
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
