version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

  core:
    build: .
    container_name: hieunt_core
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
